export const uniSeedData = [
  {
    name: "Vanderbilt University",
    state: "Tennessee",
    acceptanceRate: 6,
    minGpa: 3.8,
    tuitionUsd: 67934,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Biology",
      "Economics",
      "Engineering",
      "Medicine",
      "Music",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 2",
    websiteUrl: "https://www.vanderbilt.edu",
    descriptionText:
      "A private research university in Nashville, Tennessee, known for strong programs in engineering, music, and medicine.",
  },
  {
    name: "Johns Hopkins University",
    state: "Maryland",
    acceptanceRate: 7,
    minGpa: 3.9,
    tuitionUsd: 66670,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Biomedical Engineering",
      "Public Health",
      "International Studies",
      "Computer Science",
      "Political Science",
    ],
    applicationDeadline: "2027-01-05",
    rankTier: "Tier 2",
    websiteUrl: "https://www.jhu.edu",
    descriptionText:
      "A private university in Baltimore known for its medical school and research programs in science and engineering.",
  },
  {
    name: "Northwestern University",
    state: "Illinois",
    acceptanceRate: 7,
    minGpa: 3.8,
    tuitionUsd: 69375,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Journalism",
      "Engineering",
      "Economics",
      "Computer Science",
      "Biology",
    ],
    applicationDeadline: "2027-01-02",
    rankTier: "Tier 2",
    websiteUrl: "https://www.northwestern.edu",
    descriptionText:
      "A private university near Chicago known for its strong journalism and engineering programs.",
  },
  {
    name: "Rice University",
    state: "Texas",
    acceptanceRate: 9,
    minGpa: 3.8,
    tuitionUsd: 66540,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Engineering",
      "Architecture",
      "Music",
      "Business",
      "Biology",
    ],
    applicationDeadline: "2027-01-08",
    rankTier: "Tier 2",
    websiteUrl: "https://www.rice.edu",
    descriptionText:
      "A private research university in Houston with strong programs in engineering and architecture.",
  },
  {
    name: "University of Southern California",
    state: "California",
    acceptanceRate: 15,
    minGpa: 3.7,
    tuitionUsd: 69900,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Cinema",
      "Business",
      "Engineering",
      "Biological Sciences",
      "Communications",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 2",
    websiteUrl: "https://www.usc.edu",
    descriptionText:
      "A private university in Los Angeles known for its programs in film, business, and engineering.",
  },
  {
    name: "New York University",
    state: "New York",
    acceptanceRate: 12,
    minGpa: 3.6,
    tuitionUsd: 57500,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Business",
      "Arts",
      "Computer Science",
      "Economics",
      "Social Sciences",
    ],
    applicationDeadline: "2027-01-05",
    rankTier: "Tier 2",
    websiteUrl: "https://www.nyu.edu",
    descriptionText:
      "A large private university in New York City, strong in business, arts, and social sciences.",
  },
  {
    name: "Emory University",
    state: "Georgia",
    acceptanceRate: 18,
    minGpa: 3.8,
    tuitionUsd: 56500,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Public Health",
      "Business",
      "Biology",
      "Psychology",
      "Economics",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 2",
    websiteUrl: "https://www.emory.edu",
    descriptionText:
      "A private university in Atlanta known for its strong programs in public health and liberal arts.",
  },
  {
    name: "Washington University in St. Louis",
    state: "Missouri",
    acceptanceRate: 15,
    minGpa: 3.8,
    tuitionUsd: 61170,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Biology",
      "Business",
      "Computer Science",
      "Medicine",
      "Psychology",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 2",
    websiteUrl: "https://wustl.edu",
    descriptionText:
      "A private research university in St. Louis with strong programs in medicine and social sciences.",
  },
  {
    name: "Tulane University",
    state: "Louisiana",
    acceptanceRate: 9,
    minGpa: 3.6,
    tuitionUsd: 61000,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Public Health",
      "Business",
      "Environmental Science",
      "Architecture",
      "Music",
    ],
    applicationDeadline: "2027-01-05",
    rankTier: "Tier 2",
    websiteUrl: "https://tulane.edu",
    descriptionText:
      "A private research university in New Orleans known for public health, architecture, and music programs.",
  },
  {
    name: "Boston College",
    state: "Massachusetts",
    acceptanceRate: 24,
    minGpa: 3.7,
    tuitionUsd: 62300,
    financialAidAvail: true,
    toeflMin: 90,
    ieltsMin: 7.0,
    supportedMajors: [
      "Business",
      "Economics",
      "Biology",
      "Communication",
      "English",
    ],
    applicationDeadline: "2027-01-01",
    rankTier: "Tier 2",
    websiteUrl: "https://www.bc.edu",
    descriptionText:
      "A private Jesuit university in Chestnut Hill, Massachusetts, known for strong liberal arts and business programs.",
  },
  {
    name: "University of Notre Dame",
    state: "Indiana",
    acceptanceRate: 15,
    minGpa: 3.7,
    tuitionUsd: 63700,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.5,
    supportedMajors: [
      "Business",
      "Engineering",
      "Biology",
      "Political Science",
      "Mathematics",
    ],
    applicationDeadline: "2027-01-01",
    rankTier: "Tier 2",
    websiteUrl: "https://www.nd.edu",
    descriptionText:
      "A private Catholic university in Indiana noted for its strong undergraduate programs and campus community.",
  },
  {
    name: "Carnegie Mellon University",
    state: "Pennsylvania",
    acceptanceRate: 15,
    minGpa: 3.9,
    tuitionUsd: 58250,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Computer Science",
      "Engineering",
      "Fine Arts",
      "Business",
      "Statistics",
    ],
    applicationDeadline: "2027-01-01",
    rankTier: "Tier 2",
    websiteUrl: "https://www.cmu.edu",
    descriptionText:
      "A private research university in Pittsburgh with world-class programs in computer science and the arts.",
  },
  {
    name: "University of California, Los Angeles",
    state: "California",
    acceptanceRate: 9,
    minGpa: 3.9,
    tuitionUsd: 84623,
    financialAidAvail: false,
    toeflMin: 100,
    ieltsMin: 7.5,
    supportedMajors: [
      "Engineering",
      "Computer Science",
      "Biological Sciences",
      "Social Sciences",
      "Arts",
    ],
    applicationDeadline: "2027-11-30",
    rankTier: "Tier 3",
    websiteUrl: "https://www.ucla.edu",
    descriptionText:
      "A top public research university in Los Angeles known for research in multiple fields.",
  },
  {
    name: "University of California, Berkeley",
    state: "California",
    acceptanceRate: 11.65,
    minGpa: 3.8,
    tuitionUsd: 45627,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Computer Science",
      "Economics",
      "Biological Sciences",
      "Social Sciences",
    ],
    applicationDeadline: "2027-12-01",
    rankTier: "Tier 3",
    websiteUrl: "https://www.berkeley.edu",
    descriptionText:
      "A top public research university in Berkeley known for engineering, computer science, and social sciences.",
  },
  {
    name: "University of California, Irvine",
    state: "California",
    acceptanceRate: 19,
    minGpa: 3.5,
    tuitionUsd: 43600,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Computer Science",
      "Biological Sciences",
      "Business",
      "Social Ecology",
    ],
    applicationDeadline: "2027-11-30",
    rankTier: "Tier 3",
    websiteUrl: "https://www.uci.edu",
    descriptionText:
      "A public research university in Orange County, California, with strong programs in engineering and computer science.",
  },
  {
    name: "University of Michigan, Ann Arbor",
    state: "Michigan",
    acceptanceRate: 20,
    minGpa: 3.8,
    tuitionUsd: 63962,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Engineering",
      "Business",
      "Computer Science",
      "Psychology",
      "Medicine",
    ],
    applicationDeadline: "2027-02-01",
    rankTier: "Tier 3",
    websiteUrl: "https://www.umich.edu",
    descriptionText:
      "A major public research university in Ann Arbor, known for its engineering and business programs.",
  },
  {
    name: "University of Virginia",
    state: "Virginia",
    acceptanceRate: 25,
    minGpa: 3.7,
    tuitionUsd: 63000,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Political Science",
      "Engineering",
      "Biology",
      "Business",
      "Economics",
    ],
    applicationDeadline: "2027-01-01",
    rankTier: "Tier 3",
    websiteUrl: "https://www.virginia.edu",
    descriptionText:
      "A public research university in Charlottesville, Virginia, founded by Thomas Jefferson, strong in liberal arts and business.",
  },
  {
    name: "University of Texas at Austin",
    state: "Texas",
    acceptanceRate: 30,
    minGpa: 3.5,
    tuitionUsd: 38500,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Business",
      "Computer Science",
      "Biology",
      "Architecture",
    ],
    applicationDeadline: "2027-01-01",
    rankTier: "Tier 3",
    websiteUrl: "https://www.utexas.edu",
    descriptionText:
      "A leading public university in Austin, Texas, with strong engineering and business programs.",
  },
  {
    name: "University of Florida",
    state: "Florida",
    acceptanceRate: 39,
    minGpa: 3.3,
    tuitionUsd: 28200,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Business",
      "Medicine",
      "Agricultural Sciences",
      "Education",
    ],
    applicationDeadline: "2027-01-05",
    rankTier: "Tier 3",
    websiteUrl: "https://www.ufl.edu",
    descriptionText:
      "A public research university in Gainesville, Florida, known for its large campus and strong programs in engineering and medicine.",
  },
  {
    name: "Florida State University",
    state: "Florida",
    acceptanceRate: 36,
    minGpa: 3.0,
    tuitionUsd: 27700,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Business",
      "Film",
      "Music",
      "Meteorology",
    ],
    applicationDeadline: "2027-01-01",
    rankTier: "Tier 3",
    websiteUrl: "https://www.fsu.edu",
    descriptionText:
      "A public research university in Tallahassee, Florida, known for strong programs in meteorology, film, and music.",
  },
  {
    name: "Georgia Institute of Technology",
    state: "Georgia",
    acceptanceRate: 21,
    minGpa: 3.8,
    tuitionUsd: 33300,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Engineering",
      "Computer Science",
      "Business",
      "Architecture",
      "Physics",
    ],
    applicationDeadline: "2027-01-01",
    rankTier: "Tier 3",
    websiteUrl: "https://www.gatech.edu",
    descriptionText:
      "A public research university in Atlanta, Georgia, primarily focused on engineering and computer science.",
  },
  {
    name: "University of North Carolina at Chapel Hill",
    state: "North Carolina",
    acceptanceRate: 18,
    minGpa: 3.7,
    tuitionUsd: 36600,
    financialAidAvail: true,
    toeflMin: 90,
    ieltsMin: 7.0,
    supportedMajors: [
      "Business",
      "Journalism",
      "Biology",
      "Public Health",
      "Chemistry",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 3",
    websiteUrl: "https://www.unc.edu",
    descriptionText:
      "A public research university in Chapel Hill, North Carolina, known for its strong liberal arts and business programs.",
  },
  {
    name: "Boston University",
    state: "Massachusetts",
    acceptanceRate: 22,
    minGpa: 3.6,
    tuitionUsd: 58100,
    financialAidAvail: true,
    toeflMin: 90,
    ieltsMin: 7.5,
    supportedMajors: [
      "Communication",
      "Business",
      "Engineering",
      "Medicine",
      "Film",
    ],
    applicationDeadline: "2027-01-04",
    rankTier: "Tier 3",
    websiteUrl: "https://www.bu.edu",
    descriptionText:
      "A large private university in Boston, known for its programs in business, communications, and medical research.",
  },
  {
    name: "University of Washington",
    state: "Washington",
    acceptanceRate: 51,
    minGpa: 3.2,
    tuitionUsd: 39000,
    financialAidAvail: true,
    toeflMin: 92,
    ieltsMin: 7.0,
    supportedMajors: [
      "Computer Science",
      "Engineering",
      "Medicine",
      "Business",
      "Oceanography",
    ],
    applicationDeadline: "2027-03-01",
    rankTier: "Tier 4",
    websiteUrl: "https://www.washington.edu",
    descriptionText:
      "A public research university in Seattle, known for its strong engineering and medical programs.",
  },
  {
    name: "University of Maryland, College Park",
    state: "Maryland",
    acceptanceRate: 44,
    minGpa: 3.2,
    tuitionUsd: 31500,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Business",
      "Computer Science",
      "Public Policy",
      "Psychology",
    ],
    applicationDeadline: "2027-01-10",
    rankTier: "Tier 4",
    websiteUrl: "https://www.umd.edu",
    descriptionText:
      "A public flagship university in College Park, Maryland, strong in engineering and business.",
  },
  {
    name: "Pennsylvania State University",
    state: "Pennsylvania",
    acceptanceRate: 56,
    minGpa: 3.0,
    tuitionUsd: 37500,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Business",
      "Agriculture",
      "Veterinary Medicine",
      "Geosciences",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 4",
    websiteUrl: "https://www.psu.edu",
    descriptionText:
      "A large public university in State College, Pennsylvania, with strong engineering and agricultural programs.",
  },
  {
    name: "The Ohio State University",
    state: "Ohio",
    acceptanceRate: 56,
    minGpa: 3.0,
    tuitionUsd: 30000,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Business",
      "Psychology",
      "Medicine",
      "Agricultural Sciences",
    ],
    applicationDeadline: "2027-02-01",
    rankTier: "Tier 4",
    websiteUrl: "https://www.osu.edu",
    descriptionText:
      "A large public university in Columbus, Ohio, known for its broad range of programs and research.",
  },
  {
    name: "Purdue University",
    state: "Indiana",
    acceptanceRate: 60,
    minGpa: 3.0,
    tuitionUsd: 28000,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Agriculture",
      "Business",
      "Pharmacy",
      "Computer Science",
    ],
    applicationDeadline: "2027-02-01",
    rankTier: "Tier 4",
    websiteUrl: "https://www.purdue.edu",
    descriptionText:
      "A public university in West Lafayette, Indiana, widely recognized for its engineering and agriculture programs.",
  },
  {
    name: "University of Illinois Urbana-Champaign",
    state: "Illinois",
    acceptanceRate: 60,
    minGpa: 3.0,
    tuitionUsd: 34110,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Computer Science",
      "Business",
      "Agriculture",
      "Psychology",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 4",
    websiteUrl: "https://illinois.edu",
    descriptionText:
      "A public research university in Urbana-Champaign, Illinois, known for engineering and computer science.",
  },
  {
    name: "University of Wisconsin\u2013Madison",
    state: "Wisconsin",
    acceptanceRate: 51,
    minGpa: 3.0,
    tuitionUsd: 37000,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Agriculture",
      "Business",
      "Medicine",
      "Political Science",
    ],
    applicationDeadline: "2027-01-01",
    rankTier: "Tier 4",
    websiteUrl: "https://www.wisc.edu",
    descriptionText:
      "A public research university in Madison, Wisconsin, strong in agriculture, engineering, and social sciences.",
  },
  {
    name: "Texas A&M University",
    state: "Texas",
    acceptanceRate: 60,
    minGpa: 3.0,
    tuitionUsd: 37500,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Business",
      "Agriculture",
      "Architecture",
      "Biological Sciences",
    ],
    applicationDeadline: "2027-03-01",
    rankTier: "Tier 4",
    websiteUrl: "https://www.tamu.edu",
    descriptionText:
      "A public research university in College Station, Texas, with very large engineering and agricultural colleges.",
  },
  {
    name: "University of Minnesota, Twin Cities",
    state: "Minnesota",
    acceptanceRate: 57,
    minGpa: 3.0,
    tuitionUsd: 35000,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Biological Sciences",
      "Statistics",
      "Business",
      "Education",
    ],
    applicationDeadline: "2027-02-01",
    rankTier: "Tier 4",
    websiteUrl: "https://twin-cities.umn.edu",
    descriptionText:
      "A public research university in the Twin Cities, Minnesota, known for its science and engineering programs.",
  },
  {
    name: "Rutgers University",
    state: "New Jersey",
    acceptanceRate: 60,
    minGpa: 3.0,
    tuitionUsd: 34000,
    financialAidAvail: true,
    toeflMin: 83,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Business",
      "Biological Sciences",
      "Psychology",
      "Social Work",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 4",
    websiteUrl: "https://www.rutgers.edu",
    descriptionText:
      "The State University of New Jersey, with strong programs in engineering, pharmacy, and the social sciences.",
  },
  {
    name: "Virginia Tech",
    state: "Virginia",
    acceptanceRate: 65,
    minGpa: 3.0,
    tuitionUsd: 34000,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Architecture",
      "Business",
      "Agriculture",
      "Cybersecurity",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 4",
    websiteUrl: "https://vt.edu",
    descriptionText:
      "A public research university in Blacksburg, Virginia, known for engineering and agriculture programs.",
  },
  {
    name: "Arizona State University",
    state: "Arizona",
    acceptanceRate: 73,
    minGpa: 3.0,
    tuitionUsd: 33000,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Business",
      "Computer Science",
      "Environmental Science",
      "Journalism",
    ],
    applicationDeadline: "2027-02-01",
    rankTier: "Tier 5",
    websiteUrl: "https://www.asu.edu",
    descriptionText:
      "A public research university in Tempe, Arizona, one of the largest in the U.S., known for innovation in engineering and sustainability.",
  },
  {
    name: "University of Arizona",
    state: "Arizona",
    acceptanceRate: 85,
    minGpa: 3.0,
    tuitionUsd: 30000,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Astronomy",
      "Biological Sciences",
      "Engineering",
      "Business",
      "Agriculture",
    ],
    applicationDeadline: "2027-02-01",
    rankTier: "Tier 5",
    websiteUrl: "https://www.arizona.edu",
    descriptionText:
      "A public research university in Tucson, Arizona, known for its astronomy, optics, and biological sciences programs.",
  },
  {
    name: "Michigan State University",
    state: "Michigan",
    acceptanceRate: 78,
    minGpa: 3.0,
    tuitionUsd: 40000,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Education",
      "Business",
      "Agriculture",
      "Communication",
    ],
    applicationDeadline: "2027-02-01",
    rankTier: "Tier 5",
    websiteUrl: "https://msu.edu",
    descriptionText:
      "A public research university in East Lansing, Michigan, known for its education, agriculture, and engineering programs.",
  },
  {
    name: "University of Alabama",
    state: "Alabama",
    acceptanceRate: 85,
    minGpa: 3.0,
    tuitionUsd: 34000,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Business",
      "Engineering",
      "Education",
      "Communication",
      "Social Sciences",
    ],
    applicationDeadline: "2027-02-01",
    rankTier: "Tier 5",
    websiteUrl: "https://www.ua.edu",
    descriptionText:
      "A public university in Tuscaloosa, Alabama, known for its strong athletics and growing research programs.",
  },
  {
    name: "University of Kansas",
    state: "Kansas",
    acceptanceRate: 95,
    minGpa: 2.5,
    tuitionUsd: 23000,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Business",
      "Engineering",
      "Journalism",
      "Biological Sciences",
      "Health Professions",
    ],
    applicationDeadline: "2027-04-01",
    rankTier: "Tier 5",
    websiteUrl: "https://ku.edu",
    descriptionText:
      "A public research university in Lawrence, Kansas, with popular programs in journalism and pharmacy.",
  },
  {
    name: "Kansas State University",
    state: "Kansas",
    acceptanceRate: 97,
    minGpa: 2.5,
    tuitionUsd: 25000,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Agriculture",
      "Engineering",
      "Business",
      "Kinesiology",
      "Communication",
    ],
    applicationDeadline: "2027-04-01",
    rankTier: "Tier 5",
    websiteUrl: "https://k-state.edu",
    descriptionText:
      "A public research university in Manhattan, Kansas, known for its strong agriculture and engineering programs.",
  },
  {
    name: "University of Missouri",
    state: "Missouri",
    acceptanceRate: 77,
    minGpa: 3.0,
    tuitionUsd: 28000,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Journalism",
      "Engineering",
      "Agriculture",
      "Education",
      "Business",
    ],
    applicationDeadline: "2027-02-15",
    rankTier: "Tier 5",
    websiteUrl: "https://missouri.edu",
    descriptionText:
      "A public research university in Columbia, Missouri, known for its journalism school and agricultural research.",
  },
  {
    name: "West Virginia University",
    state: "West Virginia",
    acceptanceRate: 93,
    minGpa: 2.5,
    tuitionUsd: 26000,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Medicine",
      "Business",
      "Engineering",
      "Energy",
      "Education",
    ],
    applicationDeadline: "2027-04-01",
    rankTier: "Tier 5",
    websiteUrl: "https://www.wvu.edu",
    descriptionText:
      "A public university in Morgantown, West Virginia, with strong programs in energy and health sciences.",
  },
  {
    name: "University of Colorado Boulder",
    state: "Colorado",
    acceptanceRate: 80,
    minGpa: 3.0,
    tuitionUsd: 34000,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Environmental Engineering",
      "Computer Science",
      "Business",
      "Physics",
      "Psychology",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 4",
    websiteUrl: "https://www.colorado.edu",
    descriptionText:
      "A public research university in Boulder, Colorado, known for environmental and space science programs.",
  },
  {
    name: "University of Cincinnati",
    state: "Ohio",
    acceptanceRate: 80,
    minGpa: 3.0,
    tuitionUsd: 36000,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Cooperative Education",
      "Engineering",
      "Medicine",
      "Architecture",
      "Business",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 4",
    websiteUrl: "https://www.uc.edu",
    descriptionText:
      "A public research university in Cincinnati, Ohio, home to one of the nation's oldest cooperative education programs.",
  },
  {
    name: "University of Delaware",
    state: "Delaware",
    acceptanceRate: 65,
    minGpa: 3.0,
    tuitionUsd: 30000,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Business",
      "Marine Science",
      "Agroecology",
      "Education",
    ],
    applicationDeadline: "2027-02-01",
    rankTier: "Tier 4",
    websiteUrl: "https://www.udel.edu",
    descriptionText:
      "A public research university in Newark, Delaware, known for engineering and marine science programs.",
  },
  {
    name: "Brigham Young University",
    state: "Utah",
    acceptanceRate: 60,
    minGpa: 3.2,
    tuitionUsd: 6000,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Accounting",
      "Engineering",
      "Business",
      "Physics",
      "Family Life",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 4",
    websiteUrl: "https://www.byu.edu",
    descriptionText:
      "A private religious university in Provo, Utah, known for affordable tuition and strong undergraduate programs.",
  },
  {
    name: "University of California, Santa Barbara",
    state: "California",
    acceptanceRate: 30,
    minGpa: 3.5,
    tuitionUsd: 45600,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Physics",
      "Marine Biology",
      "Psychology",
      "Business",
    ],
    applicationDeadline: "2027-11-30",
    rankTier: "Tier 3",
    websiteUrl: "https://www.ucsb.edu",
    descriptionText:
      "A public research university in Santa Barbara, California, with highly ranked physics and marine science programs.",
  },
  {
    name: "University of California, Santa Cruz",
    state: "California",
    acceptanceRate: 50,
    minGpa: 3.0,
    tuitionUsd: 45000,
    financialAidAvail: true,
    toeflMin: 80,
    ieltsMin: 6.5,
    supportedMajors: [
      "Computer Science",
      "Astronomy",
      "Environmental Studies",
      "Biology",
      "Art",
    ],
    applicationDeadline: "2027-11-30",
    rankTier: "Tier 3",
    websiteUrl: "https://www.ucsc.edu",
    descriptionText:
      "A public research university in Santa Cruz, California, known for astronomy and interdisciplinary programs.",
  },
  {
    name: "Cornell University",
    state: "New York",
    acceptanceRate: 10,
    minGpa: 3.9,
    tuitionUsd: 60500,
    financialAidAvail: true,
    toeflMin: 100,
    ieltsMin: 7.0,
    supportedMajors: [
      "Engineering",
      "Agriculture",
      "Hotel Administration",
      "Business",
      "Natural Sciences",
    ],
    applicationDeadline: "2027-01-02",
    rankTier: "Tier 2",
    websiteUrl: "https://www.cornell.edu",
    descriptionText:
      "An Ivy League university in Ithaca, New York, known for strong programs across engineering, agriculture, and hotel management.",
  },
  {
    name: "University of Massachusetts Amherst",
    state: "Massachusetts",
    acceptanceRate: 65,
    minGpa: 3.0,
    tuitionUsd: 35000,
    financialAidAvail: true,
    toeflMin: 79,
    ieltsMin: 6.5,
    supportedMajors: [
      "Engineering",
      "Computer Science",
      "Business",
      "English",
      "Education",
    ],
    applicationDeadline: "2027-01-15",
    rankTier: "Tier 4",
    websiteUrl: "https://www.umass.edu",
    descriptionText:
      "A public research university in Amherst, Massachusetts, known for its strong engineering and business programs.",
  },
];

export const schSeedData = [
  {
    name: "Fulbright Foreign Student Program",
    amountUsd: 40000,
    renewable: false,
    gpaMin: 3.0,
    eligibleCountries: ["Worldwide"],
    degreeLevels: ["Master", "PhD"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-10-15",
    awardType: "Grant",
    applicationUrl: "https://foreign.fulbrightonline.org/apply",
    descriptionText:
      "A U.S. State Department program providing grants to international students for graduate study in the United States.",
  },
  {
    name: "Knight-Hennessy Scholars",
    amountUsd: 150000,
    renewable: false,
    gpaMin: 3.5,
    eligibleCountries: ["Worldwide"],
    degreeLevels: ["Master", "PhD"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-10-08",
    awardType: "Full",
    applicationUrl: "https://knight-hennessy.stanford.edu",
    descriptionText:
      "A Stanford University scholarship offering full funding for up to three years of graduate study for outstanding international students.",
  },
  {
    name: "AAUW International Fellowship",
    amountUsd: 25000,
    renewable: false,
    gpaMin: 3.5,
    eligibleCountries: ["Worldwide"],
    degreeLevels: ["Master", "PhD"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-09-30",
    awardType: "Grant",
    applicationUrl: "https://www.aauw.org",
    descriptionText:
      "Grants for women pursuing full-time graduate study in the U.S., up to $25,000 for Master’s and $30,000 for doctoral studies.",
  },
  {
    name: "Benjamin A. Gilman Scholarship",
    amountUsd: 5000,
    renewable: false,
    gpaMin: 2.5,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "low_income",
    eligibleMajors: ["All Majors"],
    deadline: "2027-03-01",
    awardType: "Grant",
    applicationUrl: "https://www.gilmanscholarship.org",
    descriptionText:
      "A scholarship for Pell Grant recipients to study or intern abroad, providing up to $5,000.",
  },
  {
    name: "Global UGRAD Exchange Program",
    amountUsd: 15000,
    renewable: false,
    gpaMin: 3.0,
    eligibleCountries: ["Worldwide"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-12-15",
    awardType: "Grant",
    applicationUrl: "https://www.globalugrad.org",
    descriptionText:
      "A U.S. State Department exchange program funding one semester of study in the U.S. for international undergraduate students.",
  },
  {
    name: "Hubert H. Humphrey Fellowship Program",
    amountUsd: 35000,
    renewable: false,
    gpaMin: 3.0,
    eligibleCountries: ["Worldwide"],
    degreeLevels: ["Master"],
    incomeRequirement: "any",
    eligibleMajors: [
      "Public Policy",
      "Public Health",
      "Environment",
      "Law",
      "Education",
    ],
    deadline: "2027-10-01",
    awardType: "Grant",
    applicationUrl: "https://www.humphreyfellowship.org",
    descriptionText:
      "A non-degree fellowship for experienced international professionals in public service fields, funded by the U.S. State Department.",
  },
  {
    name: "American University Emerging Global Leader Scholarship",
    amountUsd: 50000,
    renewable: true,
    gpaMin: 3.7,
    eligibleCountries: ["Worldwide"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "low_income",
    eligibleMajors: ["All Majors"],
    deadline: "2027-01-15",
    awardType: "Tuition Waiver",
    applicationUrl: "https://www.american.edu",
    descriptionText:
      "A scholarship for international undergraduates at American University covering full tuition and room and board for high-achieving civic-minded students.",
  },
  {
    name: "Rhodes Scholarship",
    amountUsd: 120000,
    renewable: false,
    gpaMin: 3.9,
    eligibleCountries: ["United States", "United Kingdom"],
    degreeLevels: ["Master", "PhD"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-10-01",
    awardType: "Full",
    applicationUrl: "https://www.rhodeshouse.ox.ac.uk",
    descriptionText:
      "A prestigious international scholarship providing full funding for two or three years of postgraduate study at Oxford University.",
  },
  {
    name: "Marshall Scholarship",
    amountUsd: 80000,
    renewable: true,
    gpaMin: 3.9,
    eligibleCountries: ["Any"],
    degreeLevels: ["Master", "PhD"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-09-30",
    awardType: "Full",
    applicationUrl: "https://www.marshallscholarship.org",
    descriptionText:
      "A British government scholarship funding up to two years of graduate study in the U.K. for American students.",
  },
  {
    name: "Mitchell Scholarship",
    amountUsd: 40000,
    renewable: true,
    gpaMin: 3.85,
    eligibleCountries: ["Any"],
    degreeLevels: ["Master"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-09-15",
    awardType: "Full",
    applicationUrl: "https://us-irelandalliance.org/mitchellscholarship",
    descriptionText:
      "A scholarship for U.S. students for one year of graduate study in Ireland, covering tuition and a living stipend.",
  },
  {
    name: "NSF Graduate Research Fellowship Program",
    amountUsd: 46000,
    renewable: true,
    gpaMin: 3.8,
    eligibleCountries: ["Any"],
    degreeLevels: ["PhD"],
    incomeRequirement: "any",
    eligibleMajors: ["Science", "Technology", "Engineering", "Mathematics"],
    deadline: "2027-10-25",
    awardType: "Grant",
    applicationUrl: "https://www.nsfgrfp.org",
    descriptionText:
      "A National Science Foundation fellowship providing three years of stipend and tuition support to graduate students in STEM fields.",
  },
  {
    name: "Gates Cambridge Scholarship",
    amountUsd: 150000,
    renewable: true,
    gpaMin: 3.9,
    eligibleCountries: ["Worldwide"],
    degreeLevels: ["Master", "PhD"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-11-15",
    awardType: "Full",
    applicationUrl: "https://www.gatescambridge.org",
    descriptionText:
      "A scholarship offering full funding for graduate study at the University of Cambridge for outstanding international students.",
  },
  {
    name: "Google Anita Borg Memorial Scholarship",
    amountUsd: 10000,
    renewable: false,
    gpaMin: 3.5,
    eligibleCountries: ["Worldwide"],
    degreeLevels: ["Bachelor", "Master"],
    incomeRequirement: "any",
    eligibleMajors: ["Computer Science", "Engineering"],
    deadline: "2027-11-01",
    awardType: "Grant",
    applicationUrl: "https://buildyourfuture.withgoogle.com/scholarships",
    descriptionText:
      "A scholarship for women pursuing degrees in computer science or related fields, providing one-time funding.",
  },
  {
    name: "Mensa Education & Research Foundation Scholarship",
    amountUsd: 1000,
    renewable: false,
    gpaMin: 3.0,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-03-15",
    awardType: "Grant",
    applicationUrl: "https://www.mensafoundation.org/what-we-do/scholarships/",
    descriptionText:
      "Various merit-based scholarships awarded by American Mensa to U.S. students with strong academic records.",
  },
  {
    name: "Coca-Cola Scholars Program Scholarship",
    amountUsd: 20000,
    renewable: false,
    gpaMin: 3.0,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-09-30",
    awardType: "Grant",
    applicationUrl: "https://www.coca-colascholarsfoundation.org/apply",
    descriptionText:
      "An achievement-based scholarship awarding $20,000 to 150 U.S. high school seniors each year for undergraduate study.",
  },
  {
    name: "Jack Kent Cooke College Scholarship",
    amountUsd: 40000,
    renewable: true,
    gpaMin: 3.5,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "low_income",
    eligibleMajors: ["All Majors"],
    deadline: "2027-02-13",
    awardType: "Grant",
    applicationUrl:
      "https://www.jkcf.org/our-scholarships/college-scholarship-program/",
    descriptionText:
      "A scholarship providing up to $40,000 per year to high-achieving low-income U.S. high school seniors for undergraduate study.",
  },
  {
    name: "SMART Scholarship for Service",
    amountUsd: 40000,
    renewable: false,
    gpaMin: 3.0,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor", "Master", "PhD"],
    incomeRequirement: "any",
    eligibleMajors: ["Science", "Technology", "Engineering", "Mathematics"],
    deadline: "2027-12-15",
    awardType: "Grant",
    applicationUrl: "https://smartscholarship.org/smart",
    descriptionText:
      "A Department of Defense scholarship funding STEM students (full tuition plus stipend) in exchange for a service obligation.",
  },
  {
    name: "Society of Women Engineers Scholarship",
    amountUsd: 15000,
    renewable: true,
    gpaMin: 3.0,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "any",
    eligibleMajors: ["Engineering", "Computer Science"],
    deadline: "2027-02-15",
    awardType: "Grant",
    applicationUrl: "https://swe.org/scholarships",
    descriptionText:
      "Scholarships awarded annually to women in engineering or computer science at U.S. colleges, ranging from $1,000 to $15,000.",
  },
  {
    name: "Barry Goldwater Scholarship",
    amountUsd: 7500,
    renewable: true,
    gpaMin: 3.7,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "any",
    eligibleMajors: ["Science", "Engineering", "Mathematics"],
    deadline: "2027-01-30",
    awardType: "Grant",
    applicationUrl: "https://goldwater.scholarsapply.org",
    descriptionText:
      "A national scholarship for U.S. undergraduates in STEM, providing up to $7,500 per year.",
  },
  {
    name: "NASA Space Grant Scholarship",
    amountUsd: 1000,
    renewable: true,
    gpaMin: 3.0,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "any",
    eligibleMajors: ["STEM"],
    deadline: "2027-01-15",
    awardType: "Grant",
    applicationUrl: "https://spacegrant.org",
    descriptionText:
      "Undergraduate scholarships for U.S. students in STEM fields funded by NASA Space Grant Consortia (approximately $1,000 per year).",
  },
  {
    name: "IEEE Undergraduate Scholarship",
    amountUsd: 3000,
    renewable: false,
    gpaMin: 3.5,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "any",
    eligibleMajors: ["Electrical Engineering"],
    deadline: "2027-03-01",
    awardType: "Grant",
    applicationUrl: "https://www.ieee.org",
    descriptionText:
      "Scholarships offered by the IEEE to U.S. students pursuing electrical engineering, typically around $3,000.",
  },
  {
    name: "Beinecke Scholarship",
    amountUsd: 34000,
    renewable: false,
    gpaMin: 3.5,
    eligibleCountries: ["Any"],
    degreeLevels: ["Master"],
    incomeRequirement: "any",
    eligibleMajors: ["Arts", "Humanities", "Social Sciences"],
    deadline: "2027-02-15",
    awardType: "Grant",
    applicationUrl: "https://www.beineckefoundation.org",
    descriptionText:
      "Provides $34,000 to college juniors to support graduate study in arts, humanities, and social sciences.",
  },
  {
    name: "Horatio Alger Scholarship Program",
    amountUsd: 25000,
    renewable: false,
    gpaMin: 2.0,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "low_income",
    eligibleMajors: ["All Majors"],
    deadline: "2027-06-01",
    awardType: "Grant",
    applicationUrl: "https://scholars.horatioalger.org",
    descriptionText:
      "Scholarship for U.S. high school seniors who have overcome adversity, providing $25,000 for college.",
  },
  {
    name: "Thomas R. Pickering Foreign Affairs Fellowship",
    amountUsd: 50000,
    renewable: true,
    gpaMin: 3.7,
    eligibleCountries: ["Any"],
    degreeLevels: ["Master", "PhD"],
    incomeRequirement: "any",
    eligibleMajors: [
      "International Relations",
      "History",
      "Economics",
      "Language Studies",
    ],
    deadline: "2027-01-15",
    awardType: "Full",
    applicationUrl: "https://pickeringfellowship.org",
    descriptionText:
      "A fellowship for U.S. students pursuing a foreign service career, covering graduate study in international affairs.",
  },
  {
    name: "Boren Scholarship",
    amountUsd: 25000,
    renewable: false,
    gpaMin: 3.2,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor", "Master"],
    incomeRequirement: "any",
    eligibleMajors: ["Languages", "International Studies"],
    deadline: "2027-01-08",
    awardType: "Grant",
    applicationUrl: "https://www.borenawards.org",
    descriptionText:
      "US government scholarship for U.S. undergrads to study abroad in areas critical to national security, providing up to $25,000.",
  },
  {
    name: "Schweitzer Fellowship Program",
    amountUsd: 75000,
    renewable: false,
    gpaMin: 3.2,
    eligibleCountries: ["Any"],
    degreeLevels: ["Master"],
    incomeRequirement: "any",
    eligibleMajors: ["Public Health", "Medicine", "Nursing", "Allied Health"],
    deadline: "2027-06-01",
    awardType: "Grant",
    applicationUrl: "https://schweitzerfellowship.org",
    descriptionText:
      "Grants (around $75,000 over two years) for U.S. graduate students in healthcare fields who commit to serving underserved communities.",
  },
  {
    name: "Rotary Global Grant Scholarship",
    amountUsd: 30000,
    renewable: false,
    gpaMin: 3.0,
    eligibleCountries: ["Worldwide"],
    degreeLevels: ["Master"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-05-31",
    awardType: "Grant",
    applicationUrl: "https://my.rotary.org/en/take-action/apply-grants",
    descriptionText:
      "Scholarships funded by Rotary clubs for graduate study abroad, providing funding for international study projects.",
  },
  {
    name: "Paul & Daisy Soros Fellowship for New Americans",
    amountUsd: 90000,
    renewable: true,
    gpaMin: 3.0,
    eligibleCountries: ["Any"],
    degreeLevels: ["Master"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-09-15",
    awardType: "Full",
    applicationUrl: "https://www.pdsoros.org/apply",
    descriptionText:
      "A fellowship for immigrants and children of immigrants in the U.S., providing up to $90,000 per year for graduate study.",
  },
  {
    name: "Pat Tillman Foundation Scholarship",
    amountUsd: 40000,
    renewable: false,
    gpaMin: 3.0,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "any",
    eligibleMajors: ["All Majors"],
    deadline: "2027-02-24",
    awardType: "Grant",
    applicationUrl: "https://pattillmanfoundation.org",
    descriptionText:
      "Scholarships of up to $40,000 for U.S. military veterans and spouses for college or graduate programs.",
  },
  {
    name: "NOAA Hollings Scholarship",
    amountUsd: 9800,
    renewable: true,
    gpaMin: 3.2,
    eligibleCountries: ["Any"],
    degreeLevels: ["Bachelor"],
    incomeRequirement: "any",
    eligibleMajors: [
      "Environmental Science",
      "Oceanography",
      "Meteorology",
      "Engineering",
    ],
    deadline: "2027-01-07",
    awardType: "Grant",
    applicationUrl:
      "https://www.noaa.gov/education/student-opportunities/hollings-scholarship",
    descriptionText:
      "A U.S. NOAA scholarship providing up to $9,800 per year to undergraduates in oceanic and atmospheric science fields, plus a summer internship at NOAA.",
  },
];
